# Generated by Django 5.2.3 on 2026-01-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='patient_phone',
            field=models.CharField(max_length=15),
        ),
    ]
