# Generated by Django 5.2.3 on 2026-02-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='appointment_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
