# Generated by Django 5.2.3 on 2026-01-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_booking_patient_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='appointment_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='doctors',
            name='end_time',
            field=models.TimeField(default='17:00'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='start_time',
            field=models.TimeField(default='09:00'),
        ),
    ]
