# Generated by Django 5.2.3 on 2026-02-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_booking_appointment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
