# Generated by Django 5.2.3 on 2026-02-14 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_doctors_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='date_of_birth',
        ),
    ]
