# Generated by Django 5.2.3 on 2026-01-29 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_doctors_end_time_doctoruser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoruser',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.doctors'),
        ),
    ]
