# Generated by Django 5.2.3 on 2026-01-29 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_doctoruser_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='staus',
            field=models.BooleanField(default=False),
        ),
    ]
