# Generated by Django 5.2.3 on 2026-01-29 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_booking_staus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='staus',
            new_name='status',
        ),
    ]
